# Generated by Django 3.0 on 2019-12-15 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seats_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold_seats', models.IntegerField(blank=True, default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Room')),
            ],
        ),
    ]
