# Generated by Django 3.0 on 2019-12-15 21:17

from django.db import migrations
from django.contrib.auth.models import User


def create_su(apps, schema_editor):
    User.objects.create_superuser(username='movietheatre_su', password='su_password')


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_su, )
    ]
