# Generated by Django 3.0 on 2019-12-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='sold_seats',
        ),
    ]
